{{- if .Values.enabled }}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: database-backup-credentials
spec:
  backendType: secretsManager
  dataFrom:
    - "{{ .Values.dbBackup.secretName }}"
{{- end }}